// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDubQoRTbD8CoAYQFT9fxrVLKYNRReUDjM',
    appId: '1:410782423422:web:2f43ac7edc0357f063fb2f',
    messagingSenderId: '410782423422',
    projectId: 'bd-calendar-76aaf',
    authDomain: 'bd-calendar-76aaf.firebaseapp.com',
    storageBucket: 'bd-calendar-76aaf.firebasestorage.app',
    measurementId: 'G-EY08LZPYF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2jwjvtLE-RLdodMVHXYkDSVe9O-DKMjY',
    appId: '1:410782423422:android:99993c85fc24302363fb2f',
    messagingSenderId: '410782423422',
    projectId: 'bd-calendar-76aaf',
    storageBucket: 'bd-calendar-76aaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ9QAkjWnlbxtAoGMmo6qT8AUHM5zJ6Qw',
    appId: '1:410782423422:ios:a0a20cd59d4d861163fb2f',
    messagingSenderId: '410782423422',
    projectId: 'bd-calendar-76aaf',
    storageBucket: 'bd-calendar-76aaf.firebasestorage.app',
    iosBundleId: 'com.example.bdGovernmetCalender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ9QAkjWnlbxtAoGMmo6qT8AUHM5zJ6Qw',
    appId: '1:410782423422:ios:a0a20cd59d4d861163fb2f',
    messagingSenderId: '410782423422',
    projectId: 'bd-calendar-76aaf',
    storageBucket: 'bd-calendar-76aaf.firebasestorage.app',
    iosBundleId: 'com.example.bdGovernmetCalender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDubQoRTbD8CoAYQFT9fxrVLKYNRReUDjM',
    appId: '1:410782423422:web:2b2033f92547144863fb2f',
    messagingSenderId: '410782423422',
    projectId: 'bd-calendar-76aaf',
    authDomain: 'bd-calendar-76aaf.firebaseapp.com',
    storageBucket: 'bd-calendar-76aaf.firebasestorage.app',
    measurementId: 'G-JLTBYQC5NP',
  );
}
